<a href="https://colab.research.google.com/github/Harshal-Bsys27/MachineLearning_prac/blob/main/DAV_EXP_1ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("student_performance.csv")
df.head()

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade
0,1,18.5,95.6,3.8,97.9,A
1,2,14.0,80.0,2.5,83.9,B
2,3,19.5,86.3,5.3,100.0,A
3,4,25.7,70.2,7.0,100.0,A
4,5,13.4,81.9,6.9,92.0,A

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 339501 entries, 0 to 339500
Data columns (total 6 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   student_id               339501 non-null  int64
 1   weekly_self_study_hours  339501 non-null  float64
 2   attendance_percentage    339501 non-null  float64
 3   class_participation      339501 non-null  float64
 4   total_score              339500 non-null  float64
 5   grade                    339500 non-null  object
dtypes: float64(4), int64(1), object(1)
memory usage: 15.5+ MB

In [ ]:
df.isnull().sum()

student_id                 0
weekly_self_study_hours    0
attendance_percentage      0
class_participation        0
total_score                1
grade                      1
dtype: int64

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
# Fill numeric column with mean
df['total_score'].fillna(df['total_score'].mean(), inplace=True)

# Fill categorical column with mode
df['grade'].fillna(df['grade'].mode()[0], inplace=True)

/tmp/ipykernel_48429/832242411.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['total_score'].fillna(df['total_score'].mean(), inplace=True)
/tmp/ipykernel_48429/832242411.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['grade'].fillna(df['grade'].mode()[0], inplace=True)

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df['grade'] = df['grade'].map({'A':4, 'B':3, 'C':2, 'D':1, 'F':0})

In [ ]:
df.isnull().sum()

student_id                 0
weekly_self_study_hours    0
attendance_percentage      0
class_participation        0
total_score                0
grade                      0
dtype: int64

In [ ]:
df.describe()

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade
count,339501.000000,339501.000000,339501.000000,339501.000000,339501.000000,339501.000000
mean,169751.000000,15.037002,84.721398,5.983478,84.276302,3.297551
std,98005.641208,6.896580,9.427087,1.956387,15.439496,0.915896
min,1.000000,0.000000,50.000000,0.000000,9.400000,0.000000
25%,84876.000000,10.300000,78.300000,4.700000,73.900000,3.000000
50%,169751.000000,15.000000,85.000000,6.000000,87.400000,4.000000
75%,254626.000000,19.700000,91.800000,7.300000,100.000000,4.000000
max,339501.000000,40.000000,100.000000,10.000000,100.000000,4.000000

In [ ]:
df.to_csv("cleaned_student_data.csv", index=False)

In [ ]:
from google.colab import files
files.download("cleaned_student_data.csv")